# Total Marks [40 Marks]

# Exercise 1: Polynomial Regression [20 Marks]

## Run the following cell to read the California Housing dataset.

In [114]:
import pandas as pd
from sklearn.datasets import fetch_california_housing

# Load the California housing dataset
california = fetch_california_housing()
df = pd.DataFrame(california.data, columns=california.feature_names)
df['PRICE'] = california.target

In [115]:
df

MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  \
0      8.3252      41.0  6.984127   1.023810       322.0  2.555556     37.88   
1      8.3014      21.0  6.238137   0.971880      2401.0  2.109842     37.86   
2      7.2574      52.0  8.288136   1.073446       496.0  2.802260     37.85   
3      5.6431      52.0  5.817352   1.073059       558.0  2.547945     37.85   
4      3.8462      52.0  6.281853   1.081081       565.0  2.181467     37.85   
...       ...       ...       ...        ...         ...       ...       ...   
20635  1.5603      25.0  5.045455   1.133333       845.0  2.560606     39.48   
20636  2.5568      18.0  6.114035   1.315789       356.0  3.122807     39.49   
20637  1.7000      17.0  5.205543   1.120092      1007.0  2.325635     39.43   
20638  1.8672      18.0  5.329513   1.171920       741.0  2.123209     39.43   
20639  2.3886      16.0  5.254717   1.162264      1387.0  2.616981     39.37   

       Longitude  PRICE  
0        -122.23  4.526  
1        -122.22  3.585  
2        -122.24  3.521  
3        -122.25  3.413  
4        -122.25  3.422  
...          ...    ...  
20635    -121.09  0.781  
20636    -121.21  0.771  
20637    -121.22  0.923  
20638    -121.32  0.847  
20639    -121.24  0.894  

[20640 rows x 9 columns]

In [116]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20640 entries, 0 to 20639
Data columns (total 9 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   MedInc      20640 non-null  float64
 1   HouseAge    20640 non-null  float64
 2   AveRooms    20640 non-null  float64
 3   AveBedrms   20640 non-null  float64
 4   Population  20640 non-null  float64
 5   AveOccup    20640 non-null  float64
 6   Latitude    20640 non-null  float64
 7   Longitude   20640 non-null  float64
 8   PRICE       20640 non-null  float64
dtypes: float64(9)
memory usage: 1.4 MB


## Select all features from the dataset except the price to be your input data. (Convert to array) [1 Mark]
## Select the price to be your target label. (Convert to array and reshape it to be column vector) [1 Mark]

In [117]:
X_df = df.loc[:, df.columns != 'PRICE']

X = X_df.to_numpy()
y = df[['PRICE']].to_numpy()

In [118]:
X

array([[   8.3252    ,   41.        ,    6.98412698, ...,    2.55555556,
          37.88      , -122.23      ],
       [   8.3014    ,   21.        ,    6.23813708, ...,    2.10984183,
          37.86      , -122.22      ],
       [   7.2574    ,   52.        ,    8.28813559, ...,    2.80225989,
          37.85      , -122.24      ],
       ...,
       [   1.7       ,   17.        ,    5.20554273, ...,    2.3256351 ,
          39.43      , -121.22      ],
       [   1.8672    ,   18.        ,    5.32951289, ...,    2.12320917,
          39.43      , -121.32      ],
       [   2.3886    ,   16.        ,    5.25471698, ...,    2.61698113,
          39.37      , -121.24      ]])

In [119]:
y

array([[4.526],
       [3.585],
       [3.521],
       ...,
       [0.923],
       [0.847],
       [0.894]])

## Create second order polynomial features. [4 Marks]

In [120]:
from sklearn.preprocessing import PolynomialFeatures

In [121]:
X_poly = PolynomialFeatures(degree=2, include_bias=False).fit_transform(X)

In [122]:
X_poly.shape

(20640, 44)

In [123]:
X_poly

array([[ 8.32520000e+00,  4.10000000e+01,  6.98412698e+00, ...,
         1.43489440e+03, -4.63007240e+03,  1.49401729e+04],
       [ 8.30140000e+00,  2.10000000e+01,  6.23813708e+00, ...,
         1.43337960e+03, -4.62724920e+03,  1.49377284e+04],
       [ 7.25740000e+00,  5.20000000e+01,  8.28813559e+00, ...,
         1.43262250e+03, -4.62678400e+03,  1.49426176e+04],
       ...,
       [ 1.70000000e+00,  1.70000000e+01,  5.20554273e+00, ...,
         1.55472490e+03, -4.77970460e+03,  1.46942884e+04],
       [ 1.86720000e+00,  1.80000000e+01,  5.32951289e+00, ...,
         1.55472490e+03, -4.78364760e+03,  1.47185424e+04],
       [ 2.38860000e+00,  1.60000000e+01,  5.25471698e+00, ...,
         1.54999690e+03, -4.77321880e+03,  1.46991376e+04]])

## Use StandardScaler to stabdardize the data [4 Marks]

In [124]:
from sklearn.preprocessing import StandardScaler

In [125]:
X_poly = StandardScaler().fit_transform(X_poly)

In [126]:
X_poly

array([[ 2.34476576,  0.98214266,  0.62855945, ...,  1.04093822,
        -1.12883099,  1.33088146],
       [ 2.33223796, -0.60701891,  0.32704136, ...,  1.03112623,
        -1.12011463,  1.32579211],
       [ 1.7826994 ,  1.85618152,  1.15562047, ...,  1.02622218,
        -1.11867837,  1.33597123],
       ...,
       [-1.14259331, -0.92485123, -0.09031802, ...,  1.81712982,
        -1.59080636,  0.81895996],
       [-1.05458292, -0.84539315, -0.04021111, ...,  1.81712982,
        -1.60298   ,  0.8694558 ],
       [-0.78012947, -1.00430931, -0.07044252, ...,  1.78650461,
        -1.57078206,  0.8290558 ]])

## Create a LinearRegression model to predict price from the polynomial features [5 Marks]

In [127]:
from sklearn.linear_model import LinearRegression

In [128]:
lr = LinearRegression()
lr.fit(X_poly, y)

LinearRegression()

In [129]:
predicted_price = lr.predict(X_poly)

In [130]:
predicted_price

array([[4.00298901],
       [3.92349228],
       [3.99012926],
       ...,
       [0.83369975],
       [0.88801566],
       [0.97559649]])

## Evaluate the model using r2_score [1 Mark]

In [131]:
from sklearn.metrics import r2_score

In [132]:
r2_score(y,predicted_price)

0.6832976293317493

## Repeat the same steps using Third order polynomial and see how the performance increases [1 Mark]

In [133]:
X_poly = PolynomialFeatures(degree=3, include_bias=False).fit_transform(X)

In [134]:
X_poly = StandardScaler().fit_transform(X_poly)

In [135]:
lr3 = LinearRegression()
lr3.fit(X_poly, y)

LinearRegression()

In [136]:
predicted_price = lr3.predict(X_poly)

In [137]:
print('r2_score:',r2_score(y,predicted_price))

r2_score: 0.7385168108924991


## Repeat the same steps using fourth order polynomial and see how the performance increases [1 Mark]

In [138]:
X_poly = PolynomialFeatures(degree=4, include_bias=False).fit_transform(X)

In [139]:
X_poly = StandardScaler().fit_transform(X_poly)

In [140]:
lr4 = LinearRegression()
lr4.fit(X_poly, y)

LinearRegression()

In [141]:
predicted_price = lr4.predict(X_poly)

In [142]:
print('r2_score:',r2_score(y,predicted_price))

r2_score: 0.7834366976772787


## Repeat the same steps using fifth order polynomial and see how the performance increases [1 Mark]

In [143]:
X_poly = PolynomialFeatures(degree=5, include_bias=False).fit_transform(X)

In [144]:
X_poly = StandardScaler().fit_transform(X_poly)

In [145]:
lr5 = LinearRegression()
lr5.fit(X_poly, y)

LinearRegression()

In [146]:
predicted_price = lr5.predict(X_poly)

In [147]:

print('r2_score:',r2_score(y,predicted_price))

r2_score: 0.8198874896583952


## Repeat the same steps using sixth order polynomial and see how the performance increases [1 Mark]

In [148]:
X_poly = PolynomialFeatures(degree=6, include_bias=False).fit_transform(X)

In [149]:
X_poly = StandardScaler().fit_transform(X_poly)

In [150]:
lr6 = LinearRegression()
lr6.fit(X_poly, y)

LinearRegression()

In [151]:
predicted_price = lr6.predict(X_poly)

In [152]:

print('r2_score:',r2_score(y,predicted_price))

r2_score: 0.8478353784609556


## Check out the number of polynomial features in the sixth order polynomial 

In [153]:
X_poly.shape

(20640, 3002)

# Exercise 2: (Using Train/Test Split - Overfitting) [20 Marks]

## Create polynomial features with degree 2 [3 Marks]

In [154]:
X_poly = PolynomialFeatures(degree=2, include_bias=False).fit_transform(X)

## Train/test split using test_size=0.33 and random_state=42 [4 Marks]

In [155]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_poly, y, test_size=0.33, random_state=42)

## Scale the training data using StandardScaler [3 Marks]

In [156]:
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)

## Use the scaled data to train a linear regression model. [3 Marks]

In [157]:
final_lr = LinearRegression()
final_lr.fit(X_train_scaled, y_train)

LinearRegression()

## Scale the test data using the trained StandardScaler. [2 Marks]

In [158]:
X_test_scaled = scaler.transform(X_test)

## Use the trained model to predict the target label for both scaled training and test data. [2 Marks]

In [159]:
y_train_pred = final_lr.predict(X_train_scaled)
y_test_pred = final_lr.predict(X_test_scaled)

## Evaluate the predictions using r2_score. [1 Mark]

In [160]:
r2_train_score = r2_score(y_train, y_train_pred)
r2_test_score = r2_score(y_test, y_test_pred)
print('r2_score Train:', r2_train_score)
print('r2_score Test:', r2_test_score)

r2_score Train: 0.6834223219945919
r2_score Test: 0.6590778165203754


## Repeat using third order polynomial and notice the test scoe [2 Marks]

In [161]:
X_poly = PolynomialFeatures(degree=3, include_bias=False).fit_transform(X)

In [162]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_poly, y, test_size=0.33, random_state=42)

In [163]:
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)

In [164]:
final_lr = LinearRegression()
final_lr.fit(X_train_scaled, y_train)

LinearRegression()

In [165]:
X_test_scaled = scaler.transform(X_test)

In [166]:
y_train_pred = final_lr.predict(X_train_scaled)
y_test_pred = final_lr.predict(X_test_scaled)

In [167]:
r2_train_score = r2_score(y_train, y_train_pred)
r2_test_score = r2_score(y_test, y_test_pred)
print('r2_score Train:', r2_train_score)
print('r2_score Test:', r2_test_score)

r2_score Train: 0.7453087038162005
r2_score Test: -13.948448207554904
